# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/e31x/e31x_pins.xdc

# XDC: imports/e31x/e31x_timing.xdc

# Block Designs: bd/e31x_ps_bd/e31x_ps_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd || ORIG_REF_NAME==e31x_ps_bd} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_axi_dma_eth_internal_0/e31x_ps_bd_axi_dma_eth_internal_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_axi_dma_eth_internal_0 || ORIG_REF_NAME==e31x_ps_bd_axi_dma_eth_internal_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_axi_protocol_convert_rx_0/e31x_ps_bd_axi_protocol_convert_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_axi_protocol_convert_rx_0 || ORIG_REF_NAME==e31x_ps_bd_axi_protocol_convert_rx_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_axi_protocol_convert_tx_0/e31x_ps_bd_axi_protocol_convert_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_axi_protocol_convert_tx_0 || ORIG_REF_NAME==e31x_ps_bd_axi_protocol_convert_tx_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_xbar_0/e31x_ps_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_xbar_0 || ORIG_REF_NAME==e31x_ps_bd_xbar_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_auto_cc_3/e31x_ps_bd_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_auto_cc_3 || ORIG_REF_NAME==e31x_ps_bd_auto_cc_3} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_auto_pc_0/e31x_ps_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_auto_pc_0 || ORIG_REF_NAME==e31x_ps_bd_auto_pc_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_auto_cc_0/e31x_ps_bd_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_auto_cc_0 || ORIG_REF_NAME==e31x_ps_bd_auto_cc_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_auto_cc_1/e31x_ps_bd_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_auto_cc_1 || ORIG_REF_NAME==e31x_ps_bd_auto_cc_1} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_auto_cc_2/e31x_ps_bd_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_auto_cc_2 || ORIG_REF_NAME==e31x_ps_bd_auto_cc_2} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_axi_interconnect_0_0/e31x_ps_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_axi_interconnect_0_0 || ORIG_REF_NAME==e31x_ps_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_processing_system7_0_0/e31x_ps_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_processing_system7_0_0 || ORIG_REF_NAME==e31x_ps_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_smartconnect_dma_0/e31x_ps_bd_smartconnect_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_smartconnect_dma_0 || ORIG_REF_NAME==e31x_ps_bd_smartconnect_dma_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_xlconcat_0_0/e31x_ps_bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_xlconcat_0_0 || ORIG_REF_NAME==e31x_ps_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_xlslice_2_0/e31x_ps_bd_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_xlslice_2_0 || ORIG_REF_NAME==e31x_ps_bd_xlslice_2_0} -quiet] -quiet

# IP: bd/e31x_ps_bd/ip/e31x_ps_bd_xlconstant_0_0/e31x_ps_bd_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==e31x_ps_bd_xlconstant_0_0 || ORIG_REF_NAME==e31x_ps_bd_xlconstant_0_0} -quiet] -quiet

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/e31x_ps_bd_ooc.xdc
