# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.srcs/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_axi_dma_eth_internal_0/e31x_ps_bd_axi_dma_eth_internal_0.xci
# IP: The module: 'e31x_ps_bd_axi_dma_eth_internal_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_axi_dma_eth_internal_0/e31x_ps_bd_axi_dma_eth_internal_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'e31x_ps_bd_axi_dma_eth_internal_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_axi_dma_eth_internal_0/e31x_ps_bd_axi_dma_eth_internal_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'e31x_ps_bd_axi_dma_eth_internal_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_axi_dma_eth_internal_0/e31x_ps_bd_axi_dma_eth_internal_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'e31x_ps_bd_axi_dma_eth_internal_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: G:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.srcs/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_axi_dma_eth_internal_0/e31x_ps_bd_axi_dma_eth_internal_0.xci
# IP: The module: 'e31x_ps_bd_axi_dma_eth_internal_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_axi_dma_eth_internal_0/e31x_ps_bd_axi_dma_eth_internal_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'e31x_ps_bd_axi_dma_eth_internal_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_axi_dma_eth_internal_0/e31x_ps_bd_axi_dma_eth_internal_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'e31x_ps_bd_axi_dma_eth_internal_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_axi_dma_eth_internal_0/e31x_ps_bd_axi_dma_eth_internal_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'e31x_ps_bd_axi_dma_eth_internal_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
