# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.srcs/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_auto_cc_1/e31x_ps_bd_auto_cc_1.xci
# IP: The module: 'e31x_ps_bd_auto_cc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_auto_cc_1/e31x_ps_bd_auto_cc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'e31x_ps_bd_auto_cc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_auto_cc_1/e31x_ps_bd_auto_cc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'e31x_ps_bd_auto_cc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.srcs/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_auto_cc_1/e31x_ps_bd_auto_cc_1.xci
# IP: The module: 'e31x_ps_bd_auto_cc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_auto_cc_1/e31x_ps_bd_auto_cc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'e31x_ps_bd_auto_cc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/FPGA/Vivado_Prj/USRP_E310/project_1/project_1.gen/sources_1/bd/e31x_ps_bd/ip/e31x_ps_bd_auto_cc_1/e31x_ps_bd_auto_cc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'e31x_ps_bd_auto_cc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
